// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication1.Models.ItemModell", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("WebApplication1.Models.UploadOrdersModell", b =>
                {
                    b.Property<int>("UploadedOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UploadedItems")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadedOrderTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UploadedTakeway")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UploadedTotalCost")
                        .HasColumnType("bigint");

                    b.HasKey("UploadedOrderId");

                    b.ToTable("upload_orders");
                });

            modelBuilder.Entity("WebApplication1.Models.Usermodell", b =>
                {
                    b.Property<long>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IntroPoints")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Uid");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
